version: '3.8'
services:
  crashroyale:
    build: .
    volumes:
      - .:/app
      - /app/bin
      - /app/obj
    stdin_open: true
    tty: true
    command: dotnet watch run --project P1ClashOfRoyale/P1ClashOfRoyale.csproj
